version: '3'

services:
  nginx:
    container_name: pw_local-serverPractica
    image: nginx:1.23.3-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    container_name: pw_local-phpPractica
    image: vcaballerosalle/pwii-php-fpm:2.0
    restart: unless-stopped
    ports:
      - "9030:9001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: pw_local-dbPractica
    image: mysql:8.0.32
    restart: unless-stopped
    ports:
      - "3330:3306"
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - .env

  admin:
    container_name: pw_local-adminPractica
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  barcode:
    container_name: pw_barcode
    restart: unless-stopped
    image: neodynamic/barcodeprowebapi:3.0.6
    ports:
      - "8020:80"

  #insert_riddles:
  # container_name: pw_insert_riddles
   # image: php:7.4-cli-alpine
  # volumes:
  #  - /src/Service/InsertRiddles.php:/src/Service/InsertRiddles.php
   # depends_on:
    #  - db
    #command: sh -c "php /src/Service/InsertRiddles.php"
    #env_file:
    #  - .env
    
